language: c

env:
  global:
  - CACHE=$HOME/.singlep-caches

cache:
  branch: md5deep
  directories:
  - "$CACHE"

before_script:
  - mkdir deploy
  - git clone https://github.com/Bots-United/hlsdk
  - git clone https://github.com/Bots-United/metamod-hl1

matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
    addons:
      apt:
        packages:
        - libc6-dev-i386
        - lib32gcc-4.8-dev
        - lib32stdc++-4.8-dev
        - g++-multilib
        - zip
    script:
      - make SDKTOP=./hlsdk METAMODDIR=./metamod-hl1/metamod
      - zip -9 -j ./deploy/singlep-mm-linux-i386.zip *.so README.md

  - os: linux
    dist: trusty
    addons:
      apt:
        packages:
        - binutils-mingw-w64-i686
        - gcc-mingw-w64-i686
        - g++-mingw-w64-i686
        - zip
    script:
      - make -fMakefile.mingw SDKTOP=./hlsdk METAMODDIR=./metamod-hl1/metamod
      - zip -9 -j ./deploy/singlep-mm-win32.zip *.dll README.md

  - os: osx
    osx_image: xcode8
    language: objective-c
    script:
      - make OPT=opt SDKTOP=./hlsdk METAMODDIR=./metamod-hl1/metamod
      - zip -9 -j ./deploy/singlep-mm-macos.zip *.dylib README.md

deploy:
  - provider: releases
    api_key:
      secure: mzTXoA51KLlBKO9ZEjbEzFQW/YOiw0WuXV3bkY2kr85n2OquhKpRK8BIOd8Vs076dzP88VbYuu4SUgz5229NeZaE/ajYQxpOiBuZMSZZUQec6nZw3Cvc5fXE5yekOs7NA6Nh0ozT12A6xxG0QXjOox/A8mxP1EVUI+O7DmI0MTXroNmqNzgUo/KqKai+Mzuv6T1X8sq4jP7W4ehrtoUx/8km7vQI7zI0IB0bqX4e7FxdHlo92s83RAJXs1bqZim4TuUa58WuAYKr+/4wTtkqyletCaotDBE7k+ULRkp/QvXUcw6ZKZmEtNbbM+neraswfxcy06Bi3+lrVG1vjSatyRJKuHpSwSq3BW9OY+L/nuP1EmM1L0O+Z8ujtslPBMDo2NFvEaoIl6jfbsllzDsrNiIf164sqSHunbaJLZ6qPQ4IfnMzYcc6/8Rn0uDfmaoHJdK+Fc0T5Rblnvlp4/qlEy9VEgJjNWxT5O4o55RqSUb7ECTDZLLwvJOwcdrzvpR+faoaJHUO5yZHjNo6czyg+Gnea6IriXGv8/ky/A7dFlzIxg/yL4pSyVfIl8Ibo0CcvZZkfOFXPU9T3cwZrOawq/oGGbV8w4kEuFC1Px+H7uJ5tCl7JN3h1A557TMTR4rZ7HGqPr9oXHBUrZIdHakSW9ra/laMvg6zXTxKlUIgaQY=
    file: deploy/*
    file_glob: true
    skip_cleanup: true
    overwrite: true
    on:
      all_branches: true
      tags: true
